---
- name: Include Debian setup
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Jellyfin package
  ansible.builtin.package:
    name: jellyfin
    state: present

- name: Ensure Jellyfin is started and enabled at boot
  ansible.builtin.service:
    name: jellyfin
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"
